import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/home/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${geistSans.className} max-w-[1000px] xl:max-w-[1280px] 2xl:max-w-[1440px] px-12 mx-auto`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
